version: '3.8'

services:
  app:
    build: .
    restart: always
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_PASSWORD: Ooaakk00!
      DB_USER: root
      DB_NAME: evershop
    networks:
      - myevershop
    depends_on:
      - database
    volumes:
      - /backup/media:/app/media
      - ./config:/app/config
      - ./translations:/app/translations
    ports:
      - 4200:3000
  
  #The postgres database: 
  database:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - /backup/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Ooaakk00!
      POSTGRES_USER: root
      POSTGRES_DB: evershop
    ports:
      - "5432:5432"
    networks:
      - myevershop

networks:
  myevershop:
    name: MyEverShop
    driver: bridge

volumes:
  postgres-data:
